### ISSUE TITLE
Does it have API?

### ISSUE THREAD

**Issue by X-Mars** [jethrocarr/namedmanager#63]
i want to creat AAA with api。how to do？

**Comment by zubfatal** [comment]
It does have a SOAP API, though (as far as I know) not documented, functionality can be found in `htdocs/api/namedmanager.*` files. The API seems to be more or less "read-only", which means there are no functions to create/remove zones or records. I am currently looking into extending this functionality myself, since I need to integrate this with something that needs to be able to create a new zone from an API request.

**Comment by X-Mars** [comment]
Thank yuo my friend， let me have a try。
